name: Java CI with Gradle

on:
  push:
    branches:
      - main  # Trigger on push to main branch (you can customize this)
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch (you can customize this)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    # Cache Gradle dependencies to speed up builds
    - name: Cache Gradle dependencies
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # Run Gradle build
    - name: Build with Gradle
      run: ./gradlew build

    # Optionally run tests
    - name: Run tests
      run: ./gradlew test
